## Relatório de Análise VI

## Criando Novas Variáveis

In [2]:
import pandas as pd

In [4]:
dados = pd.read_csv('dados/database_norte.csv', sep = ';')

In [5]:
dados

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
0,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-27,13,22945.0,0,0,0,0,0.0,0.0,0.0
1,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-28,13,22945.0,0,0,0,0,0.0,0.0,0.0
2,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-29,14,22945.0,0,0,0,0,0.0,0.0,0.0
3,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-30,14,22945.0,0,0,0,0,0.0,0.0,0.0
4,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-31,14,22945.0,0,0,0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134545,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-15,2,11540.0,1117,5,15,0,0.0,0.0,0.0
134546,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-16,2,11540.0,1125,8,15,0,0.0,0.0,0.0
134547,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-17,3,11540.0,1125,0,15,0,0.0,0.0,0.0
134548,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-18,3,11540.0,1128,3,15,0,0.0,0.0,0.0
134549,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-19,3,11540.0,1141,13,15,0,0.0,0.0,0.0

In [6]:
dados['Valor casoseObitosAcumulados'] = dados['casosNovos'] + dados['obitosNovos']

In [15]:
dados

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana,Valor casoseObitosAcumulados
0,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-27,13,22945.0,0,0,0,0,0.0,0.0,0.0,0
1,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-28,13,22945.0,0,0,0,0,0.0,0.0,0.0,0
2,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-29,14,22945.0,0,0,0,0,0.0,0.0,0.0,0
3,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-30,14,22945.0,0,0,0,0,0.0,0.0,0.0,0
4,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-31,14,22945.0,0,0,0,0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134545,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-15,2,11540.0,1117,5,15,0,0.0,0.0,0.0,5
134546,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-16,2,11540.0,1125,8,15,0,0.0,0.0,0.0,8
134547,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-17,3,11540.0,1125,0,15,0,0.0,0.0,0.0,0
134548,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-18,3,11540.0,1128,3,15,0,0.0,0.0,0.0,3
134549,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-19,3,11540.0,1141,13,15,0,0.0,0.0,0.0,13

## Excluíndo Variáveis

In [16]:
dados_aux = pd.DataFrame(dados[['regiao', 'estado', 'municipio', 'casosAcumulado', 'casosNovos','obitosNovos','emAcompanhamentoNovos','interior/metropolitana','Recuperadosnovos']])

In [17]:
dados_aux

,regiao,estado,municipio,casosAcumulado,casosNovos,obitosNovos,emAcompanhamentoNovos,interior/metropolitana,Recuperadosnovos
0,Norte,RO,Alta Floresta D'Oeste,0,0,0,0.0,0.0,0.0
1,Norte,RO,Alta Floresta D'Oeste,0,0,0,0.0,0.0,0.0
2,Norte,RO,Alta Floresta D'Oeste,0,0,0,0.0,0.0,0.0
3,Norte,RO,Alta Floresta D'Oeste,0,0,0,0.0,0.0,0.0
4,Norte,RO,Alta Floresta D'Oeste,0,0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
134545,Norte,TO,Xambioá,1117,5,0,0.0,0.0,0.0
134546,Norte,TO,Xambioá,1125,8,0,0.0,0.0,0.0
134547,Norte,TO,Xambioá,1125,0,0,0.0,0.0,0.0
134548,Norte,TO,Xambioá,1128,3,0,0.0,0.0,0.0
134549,Norte,TO,Xambioá,1141,13,0,0.0,0.0,0.0

In [18]:
del dados_aux['emAcompanhamentoNovos']

In [20]:
dados_aux

,regiao,estado,municipio,casosAcumulado,casosNovos,obitosNovos,interior/metropolitana,Recuperadosnovos
0,Norte,RO,Alta Floresta D'Oeste,0,0,0,0.0,0.0
1,Norte,RO,Alta Floresta D'Oeste,0,0,0,0.0,0.0
2,Norte,RO,Alta Floresta D'Oeste,0,0,0,0.0,0.0
3,Norte,RO,Alta Floresta D'Oeste,0,0,0,0.0,0.0
4,Norte,RO,Alta Floresta D'Oeste,0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...
134545,Norte,TO,Xambioá,1117,5,0,0.0,0.0
134546,Norte,TO,Xambioá,1125,8,0,0.0,0.0
134547,Norte,TO,Xambioá,1125,0,0,0.0,0.0
134548,Norte,TO,Xambioá,1128,3,0,0.0,0.0
134549,Norte,TO,Xambioá,1141,13,0,0.0,0.0

In [29]:
del dados_aux['obitosNovos']

In [30]:
dados_aux

,regiao,estado,municipio,casosAcumulado,casosNovos,interior/metropolitana,Recuperadosnovos
0,Norte,RO,Alta Floresta D'Oeste,0,0,0.0,0.0
1,Norte,RO,Alta Floresta D'Oeste,0,0,0.0,0.0
2,Norte,RO,Alta Floresta D'Oeste,0,0,0.0,0.0
3,Norte,RO,Alta Floresta D'Oeste,0,0,0.0,0.0
4,Norte,RO,Alta Floresta D'Oeste,0,0,0.0,0.0
...,...,...,...,...,...,...,...
134545,Norte,TO,Xambioá,1117,5,0.0,0.0
134546,Norte,TO,Xambioá,1125,8,0.0,0.0
134547,Norte,TO,Xambioá,1125,0,0.0,0.0
134548,Norte,TO,Xambioá,1128,3,0.0,0.0
134549,Norte,TO,Xambioá,1141,13,0.0,0.0

In [33]:
dados.drop(['obitosNovos', 'emAcompanhamentoNovos', 'interior/metropolitana', 'Recuperadosnovos'], axis = 1, inplace = True)

In [34]:
dados

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,Valor casoseObitosAcumulados
0,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-27,13,22945.0,0,0,0,0
1,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-28,13,22945.0,0,0,0,0
2,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-29,14,22945.0,0,0,0,0
3,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-30,14,22945.0,0,0,0,0
4,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-31,14,22945.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134545,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-15,2,11540.0,1117,5,15,5
134546,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-16,2,11540.0,1125,8,15,8
134547,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-17,3,11540.0,1125,0,15,0
134548,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-18,3,11540.0,1128,3,15,3
134549,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-19,3,11540.0,1141,13,15,13

In [35]:
dados.to_csv('dados/database_norte.csv', sep = ';', index = False)