## Relatório de Análise IV

## Seleções e Frequencias

In [1]:
import pandas as pd

In [5]:
dados = pd.read_csv('dados/database_norte.csv', sep = ';')

In [6]:
dados

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
0,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-25,9,1777225.0,0,0,0,0,NaN,NaN,NaN
1,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-26,9,1777225.0,0,0,0,0,NaN,NaN,NaN
2,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-27,9,1777225.0,0,0,0,0,NaN,NaN,NaN
3,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-28,9,1777225.0,0,0,0,0,NaN,NaN,NaN
4,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-29,9,1777225.0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137752,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-15,2,11540.0,1117,5,15,0,NaN,NaN,0.0
137753,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-16,2,11540.0,1125,8,15,0,NaN,NaN,0.0
137754,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-17,3,11540.0,1125,0,15,0,NaN,NaN,0.0
137755,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-18,3,11540.0,1128,3,15,0,NaN,NaN,0.0
137756,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-19,3,11540.0,1141,13,15,0,NaN,NaN,0.0

In [24]:
# Selecione somente os casos classificados com tipo 'AM'.
selecao = dados['estado'] == 'AM'
n1 = dados[selecao].shape[0]
n1

18868

In [25]:
# Selecione as cidades classificados com tipos 'Manaus', 'Parintins' e 'Iranduba'.
selecao = (dados['municipio'] == 'AM') | (dados['municipio'] == 'Manaus') | (dados['municipio'] == 'Parintins') | (dados['municipio'] == 'Iranduba') 
n2 = dados[selecao].shape[0]
n2

897

In [32]:
# Selecione os cidades entre 100 e 300 casos diarios confirmados, incluindo os limites.
selecao = (dados['casosNovos'] >= 100) & (dados['casosNovos'] <= 300) 
n3 = dados[selecao].shape[0]
n3

1964

In [7]:
# Selecione os cidades que tenham pelo menos casos acumulados menor que 1.000,00.

In [36]:
selecao = (dados['casosAcumulado'] >= 10000) & (dados['estado'] == 'AM')
n4 = dados[selecao].shape[0]
n4

507