## Relaório de Análise V

## Tramamento de dados

In [1]:
import pandas as pd

In [2]:
dados = pd.read_csv('dados/database_norte.csv', sep = ';')

In [5]:
dados

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
0,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-25,9,1777225.0,0,0,0,0,NaN,NaN,NaN
1,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-26,9,1777225.0,0,0,0,0,NaN,NaN,NaN
2,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-27,9,1777225.0,0,0,0,0,NaN,NaN,NaN
3,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-28,9,1777225.0,0,0,0,0,NaN,NaN,NaN
4,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-29,9,1777225.0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137752,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-15,2,11540.0,1117,5,15,0,NaN,NaN,0.0
137753,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-16,2,11540.0,1125,8,15,0,NaN,NaN,0.0
137754,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-17,3,11540.0,1125,0,15,0,NaN,NaN,0.0
137755,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-18,3,11540.0,1128,3,15,0,NaN,NaN,0.0
137756,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-19,3,11540.0,1141,13,15,0,NaN,NaN,0.0

In [7]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137757 entries, 0 to 137756
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   regiao                  137757 non-null  object
 1   estado                  137757 non-null  object
 2   municipio               134550 non-null  object
 3   coduf                   137757 non-null  int64
 4   codmun                  135447 non-null  float64
 5   codRegiaoSaude          134550 non-null  float64
 6   nomeRegiaoSaude         134550 non-null  object
 7   data                    137757 non-null  object
 8   semanaEpi               137757 non-null  int64
 9   populacaoTCU2019        136860 non-null  float64
 10  casosAcumulado          137757 non-null  int64
 11  casosNovos              137757 non-null  int64
 12  obitosAcumulado         137757 non-null  int64
 13  obitosNovos             137757 non-null  int64
 14  Recuperadosnovos        0 non-null       float64
 15  emAcompanhamentoNovos   0 non-null       float64
 16  interior/metropolitana  134550 non-null  float64
dtypes: float64(6), int64(6), object(5)
memory usage: 17.9+ MB

In [10]:
dados[dados['municipio'].isnull()]

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
0,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-25,9,1777225.0,0,0,0,0,NaN,NaN,NaN
1,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-26,9,1777225.0,0,0,0,0,NaN,NaN,NaN
2,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-27,9,1777225.0,0,0,0,0,NaN,NaN,NaN
3,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-28,9,1777225.0,0,0,0,0,NaN,NaN,NaN
4,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-29,9,1777225.0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96191,Norte,TO,NaN,17,170000.0,NaN,NaN,2021-01-15,2,NaN,0,0,0,0,NaN,NaN,NaN
96192,Norte,TO,NaN,17,170000.0,NaN,NaN,2021-01-16,2,NaN,0,0,0,0,NaN,NaN,NaN
96193,Norte,TO,NaN,17,170000.0,NaN,NaN,2021-01-17,3,NaN,0,0,0,0,NaN,NaN,NaN
96194,Norte,TO,NaN,17,170000.0,NaN,NaN,2021-01-18,3,NaN,0,0,0,0,NaN,NaN,NaN
96195,Norte,TO,NaN,17,170000.0,NaN,NaN,2021-01-19,3,NaN,0,0,0,0,NaN,NaN,NaN

In [26]:
A = dados.shape[0]
dados.dropna(subset = ['municipio'], inplace = True)
B = dados
B

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
2609,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-27,13,22945.0,0,0,0,0,NaN,NaN,0.0
2610,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-28,13,22945.0,0,0,0,0,NaN,NaN,0.0
2611,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-29,14,22945.0,0,0,0,0,NaN,NaN,0.0
2612,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-30,14,22945.0,0,0,0,0,NaN,NaN,0.0
2613,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-31,14,22945.0,0,0,0,0,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137752,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-15,2,11540.0,1117,5,15,0,NaN,NaN,0.0
137753,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-16,2,11540.0,1125,8,15,0,NaN,NaN,0.0
137754,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-17,3,11540.0,1125,0,15,0,NaN,NaN,0.0
137755,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-18,3,11540.0,1128,3,15,0,NaN,NaN,0.0
137756,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-19,3,11540.0,1141,13,15,0,NaN,NaN,0.0

## Tratamento de Dados Faltantes (Continuação)

In [38]:
dados[dados['codmun'].isnull()].shape[0]

0

In [30]:
dados.shape[0]

134550

In [41]:
dados.fillna(0, inplace = True)
dados

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
2609,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-27,13,22945.0,0,0,0,0,0.0,0.0,0.0
2610,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-28,13,22945.0,0,0,0,0,0.0,0.0,0.0
2611,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-29,14,22945.0,0,0,0,0,0.0,0.0,0.0
2612,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-30,14,22945.0,0,0,0,0,0.0,0.0,0.0
2613,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-31,14,22945.0,0,0,0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137752,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-15,2,11540.0,1117,5,15,0,0.0,0.0,0.0
137753,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-16,2,11540.0,1125,8,15,0,0.0,0.0,0.0
137754,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-17,3,11540.0,1125,0,15,0,0.0,0.0,0.0
137755,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-18,3,11540.0,1128,3,15,0,0.0,0.0,0.0
137756,Norte,TO,Xambioá,17,172210.0,17001.0,MEDIO NORTE ARAGUAIA,2021-01-19,3,11540.0,1141,13,15,0,0.0,0.0,0.0

In [42]:
dados.to_csv('dados/database_norte.csv', sep = ';', index = False)